import {
  Scholarship,
  ScholarshipProfile,
  DocumentItem,
  ScholarshipApplication,
} from "./types";

export const COMMON_REQUIRED_DOCUMENTS: DocumentItem[] = [
  {
    id: "aadhaar",
    name: "Aadhaar Card",
    description: "Must be linked to your active mobile number and seeded with NPCI for DBT transfer.",
    required: true,
    authority: "UIDAI",
    sampleTips: "Verify NPCI seeding status via your bank branch or the mAadhaar portal.",
  },
  {
    id: "marksheet",
    name: "Previous Year Marksheet",
    description: "Original/DigiLocker marksheet of previous class (Class 10 or Class 11).",
    required: true,
    authority: "State Board / CBSE",
    sampleTips: "Ensure student name matches exactly with Aadhaar card.",
  },
  {
    id: "income_cert",
    name: "Family Income Certificate",
    description: "Issued by Tehsildar or SDO valid for the current financial year.",
    required: true,
    authority: "Revenue Dept. / MahaOnline / CSC",
    sampleTips: "Income certificate must mention total annual family income from all sources.",
  },
  {
    id: "bank_passbook",
    name: "Bank Account Details (Aadhaar Seeded)",
    description: "First page of bank passbook or cancelled cheque in student's name only.",
    required: true,
    authority: "Nationalized Bank / Post Office IPPB",
    sampleTips: "Joint accounts or parent accounts are usually not accepted on MahaDBT/NSP.",
  },
  {
    id: "domicile_cert",
    name: "Maharashtra Domicile Certificate",
    description: "Proves residency in Maharashtra for state quota eligibility.",
    required: true,
    authority: "Tehsildar / Competent District Authority",
    sampleTips: "School leaving certificate mentioning birthplace in Maharashtra is sometimes accepted.",
  },
  {
    id: "caste_cert",
    name: "Caste Certificate & Caste Validity",
    description: "Mandatory for SC, ST, OBC, VJNT, and SBC reservation schemes.",
    required: false,
    authority: "Sub-Divisional Magistrate (SDM) / Scrutiny Committee",
    sampleTips: "Keep both Caste Certificate and Caste Validity Application slip ready.",
  },
  {
    id: "ration_card",
    name: "Ration Card / BPL Card",
    description: "Yellow or Orange ration card for marginal farmer or EBC verification.",
    required: false,
    authority: "Food & Civil Supplies Dept.",
    sampleTips: "Student's name should appear on the family members page.",
  },
];

export const MOCK_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "nmmss-2026",
    title: "National Means-cum-Merit Scholarship Scheme (NMMSS)",
    officialSchemeCode: "MHRD-NMMSS-2026",
    provider: "Ministry of Education (Govt. of India) & SCERT Maharashtra",
    portalName: "National Scholarship Portal (NSP)",
    portalUrl: "https://scholarships.gov.in",
    level: "Pre-Matric",
    state: "All-India",
    benefitAmount: "₹12,000 / Year",
    annualGrantRupees: 12000,
    deadline: "2026-09-26",
    daysRemaining: 4,
    urgency: "urgent",
    isGovernmentScheme: true,
    description:
      "A flagship central scheme intended to award scholarships to meritorious students of economically weaker sections to arrest dropouts after Class 8 and encourage them to continue secondary education through Class 12.",
    eligibility: {
      minMarks: 55,
      maxFamilyIncome: 350000,
      targetClasses: ["Class 9", "Class 10", "Class 11", "Class 12"],
      categories: ["General", "OBC", "SC", "ST", "VJNT", "SBC", "EWS"],
      gender: "All",
      location: "Pan-India / Maharashtra Govt & Municipal Schools",
      streams: ["All", "Science", "Commerce", "Arts"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
    ],
    applicationSteps: [
      "Register on National Scholarship Portal (scholarships.gov.in) with Aadhaar.",
      "Fill Scheme Code NMMSS and upload Class 8/9 Marksheet.",
      "Upload Tehsildar-signed family income certificate (< ₹3.5L).",
      "Get school Headmaster / Principal verification online.",
    ],
    tags: ["Central Govt", "Direct DBT", "High Urgency", "Merit-Cum-Means"],
  },
  {
    id: "mahadbt-ebc-2026",
    title: "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC)",
    officialSchemeCode: "MAHADBT-DHE-EBC-01",
    provider: "Directorate of Higher Education, Govt. of Maharashtra",
    portalName: "MahaDBT",
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    level: "Post-Matric",
    state: "Maharashtra",
    benefitAmount: "50% - 100% Tuition & Exam Fee Waiver",
    annualGrantRupees: 45000,
    deadline: "2026-10-10",
    daysRemaining: 18,
    urgency: "approaching",
    isGovernmentScheme: true,
    description:
      "Provides reimbursement of tuition and examination fees to economically backward students (EBC) taking admissions in technical, polytechnic, and higher education courses across Maharashtra.",
    eligibility: {
      minMarks: 50,
      maxFamilyIncome: 800000,
      targetClasses: ["Class 11", "Class 12", "Polytechnic Diploma", "Undergraduate", "ITI Trade"],
      categories: ["General", "OBC", "EWS", "VJNT", "SBC"],
      gender: "All",
      location: "Maharashtra Domicile Only",
      streams: ["Science", "Commerce", "Arts", "Polytechnic Diploma", "Vocational / ITI"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
      COMMON_REQUIRED_DOCUMENTS[4],
    ],
    applicationSteps: [
      "Log into MahaDBT portal with Aadhaar OTP.",
      "Select Directorate of Higher Education -> Rajarshi Shahu Maharaj EBC Scheme.",
      "Enter CAP admission ID / College registration number.",
      "Submit for institute verification.",
    ],
    tags: ["Maharashtra State", "Fee Waiver", "EBC", "MahaDBT"],
  },
  {
    id: "mahadbt-postmatric-sc-st",
    title: "Government of India Post-Matric Scholarship for SC/ST Students",
    officialSchemeCode: "MAHADBT-SJSA-SC-04",
    provider: "Social Justice and Special Assistance Dept., Maharashtra",
    portalName: "MahaDBT",
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    level: "Post-Matric",
    state: "Maharashtra",
    benefitAmount: "100% Tuition Fee + ₹1,200/mo Maintenance",
    annualGrantRupees: 32000,
    deadline: "2026-10-16",
    daysRemaining: 24,
    urgency: "approaching",
    isGovernmentScheme: true,
    description:
      "Comprehensive scholarship providing 100% tuition, development, and examination fee reimbursement plus a monthly maintenance allowance for Scheduled Caste (SC) and Scheduled Tribe (ST) students.",
    eligibility: {
      minMarks: 40,
      maxFamilyIncome: 250000,
      targetClasses: ["Class 11", "Class 12", "ITI Trade", "Polytechnic Diploma", "Undergraduate"],
      categories: ["SC", "ST"],
      gender: "All",
      location: "Maharashtra Domicile",
      streams: ["All", "Science", "Commerce", "Arts", "Vocational / ITI", "Polytechnic Diploma"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
      COMMON_REQUIRED_DOCUMENTS[4],
      COMMON_REQUIRED_DOCUMENTS[5],
    ],
    applicationSteps: [
      "Login to MahaDBT -> Social Justice Department.",
      "Upload Caste Certificate and Caste Validity Slip.",
      "Attach Tehsildar Income Certificate (< ₹2.5L).",
      "Institute scrutinizes and forwards to Social Welfare Officer.",
    ],
    tags: ["SC/ST Welfare", "100% Fee Waiver", "Monthly Stipend", "MahaDBT"],
  },
  {
    id: "aicte-pragati-2026",
    title: "AICTE Pragati Scholarship Scheme for Girl Students",
    officialSchemeCode: "AICTE-PRAGATI-GIRLS-2026",
    provider: "All India Council for Technical Education (AICTE)",
    portalName: "AICTE Portal",
    portalUrl: "https://www.aicte-pragati-saksham-gov.in",
    level: "Technical Diploma",
    state: "All-India",
    benefitAmount: "₹50,000 / Year",
    annualGrantRupees: 50000,
    deadline: "2026-10-30",
    daysRemaining: 38,
    urgency: "open",
    isGovernmentScheme: true,
    description:
      "Empowering young women to pursue technical education. Grants ₹50,000 per annum towards college fee payment, computer/laptop purchase, and stationeries for girl students entering Polytechnic or Engineering.",
    eligibility: {
      minMarks: 50,
      maxFamilyIncome: 800000,
      targetClasses: ["Polytechnic Diploma", "Undergraduate", "Class 12"],
      categories: ["General", "OBC", "SC", "ST", "VJNT", "SBC", "EWS"],
      gender: "Female",
      location: "Pan-India / AICTE Approved Institutes in Maharashtra",
      streams: ["Science", "Polytechnic Diploma", "Vocational / ITI"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
      COMMON_REQUIRED_DOCUMENTS[4],
    ],
    applicationSteps: [
      "Verify admission letter from AICTE-approved Polytechnic or College.",
      "Fill online application on AICTE National Portal.",
      "Submit declaration certificate that applicant is maximum 2 girls per family.",
      "Institute director verifies enrollment.",
    ],
    tags: ["Girl Child Special", "Technical & Diploma", "High Grant ₹50k", "National"],
  },
  {
    id: "punjabrao-deshmukh-hostel",
    title: "Dr. Punjabrao Deshmukh Vastigruh Nirvah Bhatta Yojna",
    officialSchemeCode: "MAHADBT-DTE-PD-02",
    provider: "Directorate of Technical Education, Govt. of Maharashtra",
    portalName: "MahaDBT",
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    level: "Higher Education",
    state: "Maharashtra",
    benefitAmount: "₹20,000 - ₹30,000 / Year (Hostel Maintenance)",
    annualGrantRupees: 25000,
    deadline: "2026-10-06",
    daysRemaining: 14,
    urgency: "approaching",
    isGovernmentScheme: true,
    description:
      "Hostel and food maintenance allowance for children of registered marginal farmers and EBC students admitted to professional and diploma institutions who do not get government hostel accommodation.",
    eligibility: {
      minMarks: 50,
      maxFamilyIncome: 800000,
      targetClasses: ["Class 12", "Polytechnic Diploma", "Undergraduate"],
      categories: ["General", "OBC", "EWS", "VJNT", "SBC"],
      gender: "All",
      location: "Maharashtra Domicile (Hostel / Paying Guest resident)",
      streams: ["Science", "Polytechnic Diploma", "Commerce", "Arts"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
      COMMON_REQUIRED_DOCUMENTS[4],
      COMMON_REQUIRED_DOCUMENTS[6],
    ],
    applicationSteps: [
      "Submit 7/12 land record extract (for marginal farmer category) or EBC income certificate.",
      "Provide registered hostel or private PG rent agreement/receipt.",
      "Verify on MahaDBT under Directorate of Technical Education.",
    ],
    tags: ["Hostel Allowance", "Farmer Families", "Rural Aid", "MahaDBT"],
  },
  {
    id: "pwd-postmatric-nsp",
    title: "Post-Matric Scholarship for Students with Disabilities",
    officialSchemeCode: "DEPWD-POSTMATRIC-2026",
    provider: "Dept. of Empowerment of Persons with Disabilities, Govt. of India",
    portalName: "National Scholarship Portal (NSP)",
    portalUrl: "https://scholarships.gov.in",
    level: "Post-Matric",
    state: "All-India",
    benefitAmount: "₹14,000 / Year + Equipment Grant",
    annualGrantRupees: 14000,
    deadline: "2026-11-06",
    daysRemaining: 45,
    urgency: "open",
    isGovernmentScheme: true,
    description:
      "Direct financial support and assistive device allowances for students with 40% or more disability to pursue secondary, higher secondary, and vocational technical education.",
    eligibility: {
      minMarks: 40,
      maxFamilyIncome: 250000,
      targetClasses: ["Class 11", "Class 12", "ITI Trade", "Polytechnic Diploma", "Undergraduate"],
      categories: ["General", "OBC", "SC", "ST", "VJNT", "SBC", "EWS"],
      gender: "All",
      disabilityOnly: true,
      location: "Pan-India / Maharashtra",
      streams: ["All"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
    ],
    applicationSteps: [
      "Upload UDID (Unique Disability Identity Card) or District Civil Surgeon certificate.",
      "Apply through NSP Post-Matric Disabilities window.",
      "Upload bank passbook seeded with Aadhaar.",
    ],
    tags: ["Divyangjan / PwD", "Assistive Equipment", "Central Sector", "Open"],
  },
  {
    id: "mahadbt-vjnt-obc-sbc",
    title: "Post-Matric Scholarship for VJNT, OBC & SBC Students",
    officialSchemeCode: "MAHADBT-VJNT-OBC-03",
    provider: "VJNT, OBC & SBC Welfare Dept., Govt. of Maharashtra",
    portalName: "MahaDBT",
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    level: "Post-Matric",
    state: "Maharashtra",
    benefitAmount: "100% Tuition Fee + Book Allowance",
    annualGrantRupees: 28000,
    deadline: "2026-10-13",
    daysRemaining: 21,
    urgency: "approaching",
    isGovernmentScheme: true,
    description:
      "Tuition fee reimbursement and examination fee waiver for students belonging to Other Backward Classes (OBC), Vimukta Jati (VJ), Nomadic Tribes (NT), and Special Backward Classes (SBC) in Maharashtra.",
    eligibility: {
      minMarks: 45,
      maxFamilyIncome: 150000,
      targetClasses: ["Class 11", "Class 12", "ITI Trade", "Polytechnic Diploma", "Undergraduate"],
      categories: ["OBC", "VJNT", "SBC"],
      gender: "All",
      location: "Maharashtra Domicile",
      streams: ["All", "Science", "Commerce", "Arts", "Vocational / ITI", "Polytechnic Diploma"],
    },
    requiredDocuments: [
      COMMON_REQUIRED_DOCUMENTS[0],
      COMMON_REQUIRED_DOCUMENTS[1],
      COMMON_REQUIRED_DOCUMENTS[2],
      COMMON_REQUIRED_DOCUMENTS[3],
      COMMON_REQUIRED_DOCUMENTS[4],
      COMMON_REQUIRED_DOCUMENTS[5],
    ],
    applicationSteps: [
      "Select VJNT, OBC and SBC Welfare Department on MahaDBT.",
      "Provide non-creamy layer certificate and valid income certificate.",
      "Attach verified Class 10/12 marksheets and college fee receipt.",
    ],
    tags: ["OBC / VJNT / SBC", "Tuition Waiver", "MahaDBT", "State Welfare"],
  },
];

export const DEFAULT_STUDENT_SCHOLARSHIP_PROFILE: ScholarshipProfile = {
  fullName: "Pooja Kumari",
  classLevel: "Class 12",
  marks: 78,
  familyIncome: 180000,
  category: "OBC",
  gender: "Female",
  disabilityStatus: "None",
  state: "Maharashtra",
  district: "Pune",
  stream: "Science",
  documentsOnHand: {
    aadhaar: true,
    marksheet: true,
    income_cert: true,
    bank_passbook: false, // Bank account pending NPCI seeding
    domicile_cert: true,
    caste_cert: true,
    ration_card: false,
  },
};

export const INITIAL_STUDENT_APPLICATIONS: ScholarshipApplication[] = [
  {
    id: "app-nmmss-001",
    scholarshipId: "nmmss-2026",
    scholarshipTitle: "National Means-cum-Merit Scholarship Scheme (NMMSS)",
    provider: "Ministry of Education & SCERT",
    portalName: "National Scholarship Portal (NSP)",
    portalUrl: "https://scholarships.gov.in",
    status: "documents_pending",
    applicationId: "NSP-2026-MH-94812",
    benefitAmount: "₹12,000 / Year",
    notes: "Bank passbook NPCI mapping pending with State Bank of India branch.",
    lastUpdated: "Yesterday at 4:30 PM",
  },
  {
    id: "app-ebc-002",
    scholarshipId: "mahadbt-ebc-2026",
    scholarshipTitle: "Rajarshi Chhatrapati Shahu Maharaj EBC Scheme",
    provider: "Directorate of Higher Education, Maharashtra",
    portalName: "MahaDBT",
    portalUrl: "https://mahadbt.maharashtra.gov.in",
    status: "under_review",
    applicationId: "MahaDBT-2026-EBC-44910",
    appliedDate: "Sep 12, 2026",
    benefitAmount: "100% Tuition Fee Waiver",
    notes: "Application forwarded to Institute Scrutiny Clerk. Awaiting seal.",
    lastUpdated: "3 days ago",
  },
];

