import { ClassCohort, StudentAttendanceRecord } from "./types";

export const MOCK_CLASSES: ClassCohort[] = [
  {
    id: "cls-12a",
    name: "Class 12-A",
    grade: "12",
    section: "A",
    stream: "Science & Mathematics",
    totalEnrolled: 180,
    classTeacher: "Dr. Rajesh Sharma",
    subjects: ["Mathematics", "Physics", "Chemistry", "English Core", "Computer Science"],
  },
  {
    id: "cls-10b",
    name: "Class 10-B",
    grade: "10",
    section: "B",
    stream: "General Secondary",
    totalEnrolled: 165,
    classTeacher: "Mrs. Sunita Deshmukh",
    subjects: ["Mathematics", "Science", "Social Science", "English", "Hindi"],
  },
  {
    id: "cls-11sci",
    name: "Class 11-Science",
    grade: "11",
    section: "A",
    stream: "Pre-Engineering",
    totalEnrolled: 172,
    classTeacher: "Mr. Anil Kulkarni",
    subjects: ["Mathematics", "Physics", "Chemistry", "Biology", "English"],
  },
  {
    id: "cls-iti-elec",
    name: "ITI Electrical - Batch 1",
    grade: "Vocational 1st Year",
    section: "E1",
    stream: "Electrical Trade",
    totalEnrolled: 90,
    classTeacher: "Instructor Mohan Shinde",
    subjects: ["Trade Theory", "Workshop Calculation", "Engineering Drawing", "Employability Skills"],
  },
];

export const INITIAL_STUDENTS_ROSTER: StudentAttendanceRecord[] = [
  {
    id: "std-12a-001",
    rollNumber: "12A-18",
    name: "Amit Kumar",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    gender: "Male",
    className: "Class 12-A",
    section: "A",
    currentStatus: "absent",
    overallAttendance: 63,
    consecutiveAbsences: 5,
    totalPresent: 38,
    totalAbsent: 19,
    totalLate: 3,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 82, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 76, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 69, presentDays: 3, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 63, presentDays: 2, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "high_risk",
      score: 87,
      trendSummary: "Attendance declining for 3 consecutive weeks.",
      consecutiveAbsences: 5,
      attendanceDropPercent: 22,
      academicDecline: "Mathematics score dropped 23% in recent Unit Test",
      missedAssignments: 3,
      learningInactivityDays: 10,
      reasons: [
        "5 consecutive absences",
        "Attendance dropped 22% over the last 4 weeks (82% → 63%)",
        "Assignment completion decreased (last 3 math homework sets unsubmitted)",
        "Learning activity inactive for 10 days on digital portal",
      ],
      recommendedInterventions: [
        {
          type: "contact_parent",
          title: "Contact Parent",
          description: "Dispatch urgent bilingual WhatsApp/SMS alert and record telephonic check-in with Rajesh Kumar.",
          priority: "high",
        },
        {
          type: "schedule_counselling",
          title: "Schedule Counselling",
          description: "Book session with school counsellor (Mr. Varma) to address domestic or commute hurdles.",
          priority: "high",
        },
        {
          type: "teacher_followup",
          title: "Teacher Follow-up",
          description: "Assign peer study buddy (Pooja Kumari) and provide 15-min Socratic calculus bridge drill.",
          priority: "medium",
        },
        {
          type: "monitor_progress",
          title: "Monitor Progress",
          description: "Flag on early-warning watchlist with daily attendance alert if absent tomorrow.",
          priority: "medium",
        },
      ],
    },
    parentInfo: {
      name: "Rajesh Kumar",
      relation: "Father",
      phone: "+91 98231 44819",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [
      {
        id: "int-103",
        studentId: "std-12a-001",
        type: "teacher_followup",
        title: "Attendance improved",
        notes: "Student arrived for Period 1 Calculus class. Assigned Pooja Kumari as peer mentor for missed mechanics labs.",
        date: "Sep 22",
        performedBy: "Dr. Rajesh Sharma (Class Teacher)",
        status: "Completed",
      },
      {
        id: "int-102",
        studentId: "std-12a-001",
        type: "schedule_counselling",
        title: "Counselling recommended",
        notes: "Referred to Mr. D. Varma (School Counsellor) for commute hardship mitigation and exam anxiety support.",
        date: "Sep 21",
        performedBy: "Dr. Rajesh Sharma",
        status: "Scheduled",
      },
      {
        id: "int-101",
        studentId: "std-12a-001",
        type: "contact_parent",
        title: "Teacher contacted parent",
        notes: "Outgoing WhatsApp alert sent & call placed to father (Rajesh Kumar). Father explained harvesting season demands and promised regular attendance.",
        date: "Sep 20",
        performedBy: "Dr. Rajesh Sharma",
        status: "Completed",
      },
    ],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 48 },
      { subject: "Physics", score: 54 },
      { subject: "Chemistry", score: 62 },
      { subject: "English Core", score: 70 },
    ],
    missedAssignmentsList: [
      {
        id: "asg-01",
        title: "Problem Set 4: Quadratic Equations & Derivatives",
        subject: "Mathematics",
        dueDate: "Sep 15, 2026",
        status: "Overdue",
      },
      {
        id: "asg-02",
        title: "Physics Lab Experiment 3: Verification of Ohm's Law",
        subject: "Physics",
        dueDate: "Sep 18, 2026",
        status: "Overdue",
      },
      {
        id: "asg-03",
        title: "Chemistry Homework: Functional Group Reactions",
        subject: "Chemistry",
        dueDate: "Sep 20, 2026",
        status: "Overdue",
      },
    ],
    scholarshipInfo: {
      schemeName: "MahaDBT Post-Matric Scholarship for OBC Students",
      matchPercentage: 94,
      deadline: "Sep 30, 2026 (8 days left)",
      status: "Documents Pending",
      actionRequired: "Tehsildar Income Certificate (< ₹2.5L) needs upload before Sep 30 cutoff.",
    },
    recentAlertsList: [
      {
        id: "alt-01",
        date: "Today, 08:45 AM",
        title: "Consecutive Absence Flag",
        type: "high",
        description: "5 consecutive absences recorded. Automated parent WhatsApp notification dispatched.",
      },
      {
        id: "alt-02",
        date: "Yesterday, 03:30 PM",
        title: "Academic Risk Alert",
        type: "medium",
        description: "Unit Test mathematics score fell below 50% threshold (48%). Remedial drill suggested.",
      },
      {
        id: "alt-03",
        date: "Sep 19, 10:15 AM",
        title: "Scholarship Deadline Alert",
        type: "info",
        description: "MahaDBT scheme application closing in 11 days. Documents pending upload.",
      },
    ],
    learningProgressDetails: {
      overallCompletion: 52,
      activeDaysStreak: 1,
      practiceQuestionsSolved: 142,
      hoursSpentThisMonth: 18.5,
      strongTopic: "Basic Algebra & Vectors",
      weakTopic: "Differential Calculus & Quadratic Equations",
    },
  },
  {
    id: "std-12a-002",
    rollNumber: "12A-34",
    name: "Vikram Chauhan",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    gender: "Male",
    className: "Class 12-A",
    section: "A",
    currentStatus: "late",
    overallAttendance: 68,
    consecutiveAbsences: 2,
    totalPresent: 41,
    totalAbsent: 15,
    totalLate: 4,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 88, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 81, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 73, presentDays: 3, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 68, presentDays: 3, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "declining",
      score: 64,
      trendSummary: "Attendance declining for 3 consecutive weeks.",
      consecutiveAbsences: 2,
      attendanceDropPercent: 20,
      academicDecline: "Physics lab practical submissions overdue",
      missedAssignments: 2,
      learningInactivityDays: 6,
      reasons: [
        "Attendance dropped 20% in 1 month (88% → 68%)",
        "Attendance declining for 3 consecutive weeks",
        "2 consecutive days late to morning period",
        "Missed 2 consecutive Physics homework assignments",
      ],
      recommendedInterventions: [
        {
          type: "teacher_followup",
          title: "Teacher Follow-up",
          description: "Conduct 10-minute check-in after 4th period regarding morning transport challenges.",
          priority: "high",
        },
        {
          type: "contact_parent",
          title: "Contact Parent",
          description: "Inform mother (Sunita Chauhan) about morning tardiness pattern.",
          priority: "medium",
        },
      ],
    },
    parentInfo: {
      name: "Sunita Chauhan",
      relation: "Mother",
      phone: "+91 94220 78192",
      preferredLanguage: "Marathi",
    },
    interventionHistory: [
      {
        id: "int-201",
        studentId: "std-12a-002",
        type: "teacher_followup",
        title: "Morning check-in logged",
        notes: "Spoke with Vikram regarding bus schedule from rural depot. Shifted first-period assignment grace window by 10 mins.",
        date: "Sep 21",
        performedBy: "Dr. Rajesh Sharma",
        status: "Completed",
      },
    ],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 62 },
      { subject: "Physics", score: 55 },
      { subject: "Chemistry", score: 66 },
      { subject: "English Core", score: 74 },
    ],
    missedAssignmentsList: [
      {
        id: "asg-04",
        title: "Optics Numerical Worksheet",
        subject: "Physics",
        dueDate: "Sep 19, 2026",
        status: "Overdue",
      },
    ],
    scholarshipInfo: {
      schemeName: "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Yojna",
      matchPercentage: 88,
      deadline: "Oct 10, 2026",
      status: "Eligible - Action Required",
      actionRequired: "Application draft ready; needs student signature and domicile certificate.",
    },
    recentAlertsList: [
      {
        id: "alt-04",
        date: "Today, 09:10 AM",
        title: "Late Entry Flagged",
        type: "medium",
        description: "Arrived 25 minutes late for Period 1 Physics class (4th tardiness this month).",
      },
    ],
    learningProgressDetails: {
      overallCompletion: 64,
      activeDaysStreak: 3,
      practiceQuestionsSolved: 210,
      hoursSpentThisMonth: 24,
      strongTopic: "Thermodynamics",
      weakTopic: "Wave Optics",
    },
  },
  {
    id: "std-12a-003",
    rollNumber: "12A-09",
    name: "Sunita Yadav",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    gender: "Female",
    className: "Class 12-A",
    section: "A",
    currentStatus: "present",
    overallAttendance: 71,
    consecutiveAbsences: 0,
    totalPresent: 44,
    totalAbsent: 14,
    totalLate: 2,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 85, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 80, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 75, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 71, presentDays: 3, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "declining",
      score: 58,
      trendSummary: "Attendance declining for 3 consecutive weeks.",
      consecutiveAbsences: 0,
      attendanceDropPercent: 14,
      academicDecline: "Chemistry quiz score dropped by 12%",
      missedAssignments: 1,
      learningInactivityDays: 5,
      reasons: [
        "Attendance declining for 3 consecutive weeks (85% → 71%)",
        "Repeated Monday and Friday absences recorded (4 instances)",
        "Portal practice sessions dropped from 4/week to 1/week",
      ],
      recommendedInterventions: [
        {
          type: "schedule_counselling",
          title: "Schedule Counselling",
          description: "Check if domestic caregiving responsibilities on weekends are impacting school days.",
          priority: "medium",
        },
      ],
    },
    parentInfo: {
      name: "Rameshwar Yadav",
      relation: "Father",
      phone: "+91 97654 32110",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 68 },
      { subject: "Physics", score: 65 },
      { subject: "Chemistry", score: 58 },
      { subject: "English Core", score: 78 },
    ],
    scholarshipInfo: {
      schemeName: "AICTE Pragati Scholarship for Girl Students",
      matchPercentage: 91,
      deadline: "Oct 30, 2026",
      status: "Applied",
      actionRequired: "Application verified by College Nodal Officer.",
    },
    learningProgressDetails: {
      overallCompletion: 70,
      activeDaysStreak: 4,
      practiceQuestionsSolved: 285,
      hoursSpentThisMonth: 31,
      strongTopic: "Inorganic Chemistry",
      weakTopic: "Equilibrium Numericals",
    },
  },
  {
    id: "std-12a-004",
    rollNumber: "12A-27",
    name: "Neha Gupta",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    gender: "Female",
    className: "Class 12-A",
    section: "A",
    currentStatus: "absent",
    overallAttendance: 58,
    consecutiveAbsences: 6,
    totalPresent: 34,
    totalAbsent: 22,
    totalLate: 2,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 78, presentDays: 4, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 69, presentDays: 3, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 60, presentDays: 2, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 58, presentDays: 1, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "high_risk",
      score: 91,
      trendSummary: "Critical attendance decline: 6 consecutive absences.",
      consecutiveAbsences: 6,
      attendanceDropPercent: 20,
      academicDecline: "Missed midterm practical exam",
      missedAssignments: 4,
      learningInactivityDays: 14,
      reasons: [
        "6 consecutive absences",
        "Attendance dropped 20% in past month (78% → 58%)",
        "Zero portal engagement for 14 straight days",
        "Possible seasonal agricultural/family migration flagged by municipal records",
      ],
      recommendedInterventions: [
        {
          type: "contact_parent",
          title: "Contact Parent",
          description: "Immediate voice call to guardian. Verify current residential status.",
          priority: "high",
        },
      ],
    },
    parentInfo: {
      name: "Radhika Gupta",
      relation: "Mother",
      phone: "+91 93211 44556",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [
      {
        id: "int-301",
        studentId: "std-12a-004",
        type: "contact_parent",
        title: "Call Logged (Unanswered)",
        notes: "Outgoing call placed by Class Teacher; phone unreachable. Scheduled physical home visit with Municipal Education worker.",
        date: "Sep 20",
        performedBy: "Dr. Rajesh Sharma",
        status: "In Progress",
      },
    ],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 42 },
      { subject: "Physics", score: 49 },
      { subject: "Chemistry", score: 53 },
      { subject: "English Core", score: 65 },
    ],
    missedAssignmentsList: [
      {
        id: "asg-05",
        title: "Midterm Physics Practical Record",
        subject: "Physics",
        dueDate: "Sep 14, 2026",
        status: "Overdue",
      },
      {
        id: "asg-06",
        title: "Algebra Assignment 4",
        subject: "Mathematics",
        dueDate: "Sep 16, 2026",
        status: "Overdue",
      },
    ],
    learningProgressDetails: {
      overallCompletion: 38,
      activeDaysStreak: 0,
      practiceQuestionsSolved: 80,
      hoursSpentThisMonth: 8,
      strongTopic: "English Grammar",
      weakTopic: "Calculus & Organic Chemistry",
    },
  },
  {
    id: "std-12a-005",
    rollNumber: "12A-02",
    name: "Pooja Kumari",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    gender: "Female",
    className: "Class 12-A",
    section: "A",
    currentStatus: "present",
    overallAttendance: 94,
    consecutiveAbsences: 0,
    totalPresent: 57,
    totalAbsent: 2,
    totalLate: 1,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 92, presentDays: 6, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 95, presentDays: 5, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 93, presentDays: 5, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 94, presentDays: 5, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "regular",
      score: 8,
      trendSummary: "Consistent attendance above 90% benchmark.",
      consecutiveAbsences: 0,
      attendanceDropPercent: 0,
      academicDecline: "None (Top 5% in Chemistry & Physics)",
      missedAssignments: 0,
      learningInactivityDays: 0,
      reasons: [
        "Consistent attendance above 90% statutory benchmark",
        "Zero consecutive absences",
        "Active daily practice on digital platform",
        "Scholarship applications on track (MahaDBT 94% Match)",
      ],
      recommendedInterventions: [
        {
          type: "monitor_progress",
          title: "Monitor Progress",
          description: "Routine tracking. Encourage peer mentorship role.",
          priority: "low",
        },
      ],
    },
    parentInfo: {
      name: "Suresh Kumar",
      relation: "Father",
      phone: "+91 98111 22334",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [
      {
        id: "int-401",
        studentId: "std-12a-005",
        type: "teacher_followup",
        title: "Peer Mentor Appointment",
        notes: "Appointed Pooja as academic buddy for Amit Kumar in Calculus and Physics.",
        date: "Sep 22",
        performedBy: "Dr. Rajesh Sharma",
        status: "Completed",
      },
    ],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 88 },
      { subject: "Physics", score: 92 },
      { subject: "Chemistry", score: 94 },
      { subject: "English Core", score: 89 },
    ],
    missedAssignmentsList: [],
    scholarshipInfo: {
      schemeName: "National Means-cum-Merit Scholarship (NMMSS)",
      matchPercentage: 96,
      deadline: "Sep 26, 2026 (4 days left)",
      status: "Applied",
      actionRequired: "Application successfully submitted on National Scholarship Portal.",
    },
    recentAlertsList: [
      {
        id: "alt-05",
        date: "Yesterday",
        title: "Peer Mentorship Activated",
        type: "info",
        description: "Assigned as peer study mentor for Class 12-A calculus study group.",
      },
    ],
    learningProgressDetails: {
      overallCompletion: 92,
      activeDaysStreak: 18,
      practiceQuestionsSolved: 620,
      hoursSpentThisMonth: 64,
      strongTopic: "Optics & Thermodynamics",
      weakTopic: "None (Consistent performer)",
    },
  },
  {
    id: "std-12a-006",
    rollNumber: "12A-15",
    name: "Rahul Sharma",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    gender: "Male",
    className: "Class 12-A",
    section: "A",
    currentStatus: "present",
    overallAttendance: 89,
    consecutiveAbsences: 0,
    totalPresent: 53,
    totalAbsent: 5,
    totalLate: 2,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 88, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 90, presentDays: 5, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 89, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 89, presentDays: 5, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "regular",
      score: 14,
      trendSummary: "Stable attendance trajectory with active classroom participation.",
      consecutiveAbsences: 0,
      attendanceDropPercent: 0,
      academicDecline: "None",
      missedAssignments: 0,
      learningInactivityDays: 1,
      reasons: [
        "Stable attendance across all 4 weeks",
        "Completed all homework assignments on schedule",
        "Regular attendance in laboratory sessions",
      ],
      recommendedInterventions: [
        {
          type: "monitor_progress",
          title: "Monitor Progress",
          description: "Routine tracking.",
          priority: "low",
        },
      ],
    },
    parentInfo: {
      name: "Mukesh Sharma",
      relation: "Father",
      phone: "+91 98765 43210",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 82 },
      { subject: "Physics", score: 84 },
      { subject: "Chemistry", score: 79 },
      { subject: "English Core", score: 85 },
    ],
  },
  {
    id: "std-12a-007",
    rollNumber: "12A-21",
    name: "Sneha Patil",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    gender: "Female",
    className: "Class 12-A",
    section: "A",
    currentStatus: "present",
    overallAttendance: 87,
    consecutiveAbsences: 0,
    totalPresent: 52,
    totalAbsent: 6,
    totalLate: 2,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 86, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 88, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 87, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 87, presentDays: 4, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "regular",
      score: 18,
      trendSummary: "Meets statutory 85%+ threshold with consistent attendance.",
      consecutiveAbsences: 0,
      attendanceDropPercent: 0,
      academicDecline: "Minor drop in Thermodynamics quiz",
      missedAssignments: 0,
      learningInactivityDays: 2,
      reasons: [
        "Consistent attendance above 85% requirement",
        "No multi-day absences recorded",
      ],
      recommendedInterventions: [
        {
          type: "monitor_progress",
          title: "Monitor Progress",
          description: "Standard tracking.",
          priority: "low",
        },
      ],
    },
    parentInfo: {
      name: "Anand Patil",
      relation: "Father",
      phone: "+91 97300 11223",
      preferredLanguage: "Marathi",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 75 },
      { subject: "Physics", score: 80 },
      { subject: "Chemistry", score: 83 },
      { subject: "English Core", score: 88 },
    ],
  },
  {
    id: "std-12a-008",
    rollNumber: "12A-41",
    name: "Rohan Deshmukh",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    gender: "Male",
    className: "Class 12-A",
    section: "A",
    currentStatus: "absent",
    overallAttendance: 66,
    consecutiveAbsences: 3,
    totalPresent: 39,
    totalAbsent: 17,
    totalLate: 4,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 80, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 75, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 70, presentDays: 3, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 66, presentDays: 2, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "declining",
      score: 72,
      trendSummary: "Attendance declining for 3 consecutive weeks.",
      consecutiveAbsences: 3,
      attendanceDropPercent: 14,
      academicDecline: "Computer Science project submission pending",
      missedAssignments: 2,
      learningInactivityDays: 7,
      reasons: [
        "Attendance declining for 3 consecutive weeks (80% → 66%)",
        "3 consecutive absences recorded this week",
        "Missed 2 major practical lab sessions",
        "Learning activity inactive for 7 days",
      ],
      recommendedInterventions: [
        {
          type: "contact_parent",
          title: "Contact Parent",
          description: "Call guardian to inquire about health/transport issue.",
          priority: "high",
        },
      ],
    },
    parentInfo: {
      name: "Vikas Deshmukh",
      relation: "Father",
      phone: "+91 98223 99887",
      preferredLanguage: "Marathi",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 64 },
      { subject: "Physics", score: 61 },
      { subject: "Chemistry", score: 59 },
      { subject: "English Core", score: 71 },
    ],
  },
  {
    id: "std-12a-009",
    rollNumber: "12A-05",
    name: "Aman Shaikh",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    gender: "Male",
    className: "Class 12-A",
    section: "A",
    currentStatus: "present",
    overallAttendance: 91,
    consecutiveAbsences: 0,
    totalPresent: 55,
    totalAbsent: 4,
    totalLate: 1,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 90, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 92, presentDays: 5, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 91, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 91, presentDays: 5, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "regular",
      score: 12,
      trendSummary: "Consistent attendance with strong laboratory performance.",
      consecutiveAbsences: 0,
      attendanceDropPercent: 0,
      academicDecline: "None",
      missedAssignments: 0,
      learningInactivityDays: 0,
      reasons: [
        "Consistent attendance above 90%",
        "Active daily problem solving",
      ],
      recommendedInterventions: [
        {
          type: "monitor_progress",
          title: "Monitor Progress",
          description: "Routine tracking.",
          priority: "low",
        },
      ],
    },
    parentInfo: {
      name: "Farooq Shaikh",
      relation: "Father",
      phone: "+91 99201 33445",
      preferredLanguage: "Urdu",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 86 },
      { subject: "Physics", score: 85 },
      { subject: "Chemistry", score: 88 },
      { subject: "English Core", score: 84 },
    ],
  },
  {
    id: "std-12a-010",
    rollNumber: "12A-30",
    name: "Divya Mishra",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    gender: "Female",
    className: "Class 12-A",
    section: "A",
    currentStatus: "late",
    overallAttendance: 74,
    consecutiveAbsences: 1,
    totalPresent: 44,
    totalAbsent: 11,
    totalLate: 5,
    weeklyTrend: [
      { weekLabel: "Week 1", percentage: 84, presentDays: 5, totalDays: 6 },
      { weekLabel: "Week 2", percentage: 79, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 3", percentage: 75, presentDays: 4, totalDays: 5 },
      { weekLabel: "Week 4", percentage: 74, presentDays: 3, totalDays: 5 },
    ],
    earlyWarning: {
      riskLevel: "declining",
      score: 55,
      trendSummary: "Hovering just below statutory 75% threshold.",
      consecutiveAbsences: 1,
      attendanceDropPercent: 10,
      academicDecline: "Average score 68% (stable)",
      missedAssignments: 1,
      learningInactivityDays: 3,
      reasons: [
        "Attendance slipped below 75% threshold (currently 74%)",
        "5 instances of late arrival to first period",
        "Declined from 84% in Week 1 to 74% in Week 4",
      ],
      recommendedInterventions: [
        {
          type: "teacher_followup",
          title: "Teacher Follow-up",
          description: "Discuss bus connectivity schedule with student.",
          priority: "medium",
        },
      ],
    },
    parentInfo: {
      name: "Alok Mishra",
      relation: "Father",
      phone: "+91 98670 12345",
      preferredLanguage: "Hindi",
    },
    interventionHistory: [],
    academicSubjectMastery: [
      { subject: "Mathematics", score: 71 },
      { subject: "Physics", score: 68 },
      { subject: "Chemistry", score: 72 },
      { subject: "English Core", score: 79 },
    ],
  },
];

